import localFont from "next/font/local";
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";
import { Inter } from 'next/font/google'
import { IntlProvider } from "react-intl";
const geistSans = localFont({
  src: "./fonts/TestUntitledSerif-Bold-BF664576c439263.otf",
  variable: "--font-untitled-sans",
  weight: "400 700",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
 
  return (
   
    <html lang="en">
      <body
        className={inter.className}

      >
        {<Header/>}
        
        {children}
        <Footer/>
      </body>
    </html>
   
  );
}
